# Generated by Django 2.1 on 2020-02-16 07:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wards', '0002_remove_post_trip_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='live_link',
            field=models.CharField(default=datetime.datetime(2020, 2, 16, 7, 44, 45, 549749, tzinfo=utc), max_length=1000),
            preserve_default=False,
        ),
    ]
